name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v14
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Build
        run: |
          rake build
      - name: Lint
        run: |
          deno lint
          deno fmt --check
      - name: Run test
        run: |
          rake test:download
          deno test -A
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          deno publish
